**Name:** Finley Hardie

In [44]:
##1

In [45]:
data = pd.Series(
    [74, 63, None, 72, 68],
    name="Height",
    index=["Bob", "Toni", "Ervin", "Toby", "Min"]
)

In [46]:
import pandas as pd

In [47]:
data.name

'Height'

In [48]:
data.index

Index(['Bob', 'Toni', 'Ervin', 'Toby', 'Min'], dtype='object')

In [49]:
data.index[2]

'Ervin'

In [50]:
data.iloc[3]

np.float64(72.0)

In [51]:
data.dropna()

Bob     74.0
Toni    63.0
Toby    72.0
Min     68.0
Name: Height, dtype: float64

In [52]:
data.mean()

np.float64(69.25)

In [53]:
##2

In [54]:
df_IC = pd.read_csv("IceCreamData.csv")
df_IC.head()

   Customer      Type     Flavor  Age  Sales    Store
0         1     Adult  Chocolate   45   4.25  Greeley
1         2     Child    Vanilla    5   2.90  Greeley
2         3  Teenager  Chocolate   14   3.10   Parker
3         4     Adult    Vanilla   23   3.25   Denver
4         5     Adult  Chocolate   47   4.10   Denver

In [55]:
df_IC.dtypes

Customer      int64
Type         object
Flavor       object
Age           int64
Sales       float64
Store        object
dtype: object

In [56]:
df_IC["Age"].head()

0    45
1     5
2    14
3    23
4    47
Name: Age, dtype: int64

In [57]:
df_IC["Type"].head()

0       Adult
1       Child
2    Teenager
3       Adult
4       Adult
Name: Type, dtype: object

In [58]:
df_IC[["Age", "Type"]].tail()

    Age      Type
32   60     Adult
33   28     Adult
34   40     Adult
35    5     Child
36   14  Teenager

In [59]:
df_IC[df_IC["Type"] == "Adult"].head()

    Customer   Type     Flavor  Age  Sales    Store
0          1  Adult  Chocolate   45   4.25  Greeley
3          4  Adult    Vanilla   23   3.25   Denver
4          5  Adult  Chocolate   47   4.10   Denver
6          7  Adult  Chocolate   41   3.50   Parker
13        14  Adult    Vanilla   72   3.75   Denver

In [60]:
df_IC["Age"].mean()

np.float64(23.675675675675677)

In [61]:
df_IC.loc[df_IC["Type"] == "Adult", "Age"].mean()

np.float64(42.93333333333333)

In [62]:
df_IC["Type"].value_counts()

Type
Adult       15
Teenager    12
Child       10
Name: count, dtype: int64

In [63]:
df_IC.describe()

        Customer        Age      Sales
count  37.000000  37.000000  35.000000
mean   19.000000  23.675676   3.520000
std    10.824355  18.452723   0.546674
min     1.000000   4.000000   2.500000
25%    10.000000   6.000000   3.000000
50%    19.000000  16.000000   3.750000
75%    28.000000  40.000000   4.000000
max    37.000000  72.000000   4.300000

In [64]:
df_IC.drop(columns=["Customer"]).describe(include="object")

         Type     Flavor   Store
count      37         37      37
unique      3          2       3
top     Adult  Chocolate  Parker
freq       15         19      16

In [39]:
##3 mean_age = df_IC["Age"].mean()
print(f"The {df_IC['Age'].name} mean is: {mean_age:.2f}")

The Age mean is: 23.68

In [31]:
df_IC["Type"].unique()

array(['Adult', 'Child', 'Teenager'], dtype=object)

In [32]:
types_list = df_IC["Type"].unique()
types_string = ""

for t in types_list:
    types_string += t + " "

types_string = types_string.strip()

print(f"The Types are: {types_string}")

The Types are: Adult Child Teenager

In [33]:
type_counts = df_IC["Type"].value_counts()
type_counts

Type
Adult       15
Teenager    12
Child       10
Name: count, dtype: int64

In [34]:
type_counts.iloc[1]

np.int64(12)

In [35]:
type_counts.index[1]

'Teenager'

In [36]:
counts_string = ""

for label, count in type_counts.items():
    counts_string += f"{label}: {count} "

counts_string = counts_string.strip()

print(f"The Type counts are: {counts_string}")

The Type counts are: Adult: 15 Teenager: 12 Child: 10

In [40]:
##4

In [41]:
def create_mean(series):
    mean_val = series.mean()
    col_name = series.name if series.name is not None else "entered data"
    return f"The mean of the {col_name} is: {mean_val:.2f}"

create_mean(df_IC["Age"])

'The mean of the Age is: 23.68'

In [42]:
##5

In [43]:
def create_value_counts(series):
    vc = series.value_counts()
    col_name = series.name if series.name is not None else "entered data"
    
    parts = ""
    for label, count in vc.items():
        parts += f"{label}: {count} "
    
    parts = parts.strip()
    
    return f"The {col_name} counts are: {parts}"

create_value_counts(df_IC["Type"])

'The Type counts are: Adult: 15 Teenager: 12 Child: 10'