In [6]:
##1

In [1]:
names = ["Alex", "Jamie", "Chris", "Taylor", "Jordan"]

In [2]:
names?

Type:        list
String form: ['Alex', 'Jamie', 'Chris', 'Taylor', 'Jordan']
Length:      5
Docstring:
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [3]:
print(names[0])

Alex

In [4]:
print(names[1])

Jamie

In [5]:
for i in range(len(names)):
    print(names[i])

Alex
Jamie
Chris
Taylor
Jordan

In [7]:
##2

In [8]:
import numpy as np

In [9]:
myArray = np.random.normal(100, 10, 100)

In [10]:
print(myArray[:30])

[110.00433948  88.35213184 112.89769526 110.87724884  95.52536648
  86.22699642  90.22133688  91.47884884  95.65539501  84.73039357
  92.89019668 104.95324614 105.40594267 108.65970618  91.85068817
  99.69218774  97.9300615  107.05150157  98.74747707 104.90828332
  90.49855767 110.32633354 101.14771324 107.19983627  94.41334788
 108.92273567  87.10576002 105.21681358 111.59880986 102.91737653]

In [11]:
import pandas as pd

In [12]:
mydf = pd.DataFrame({
    "employees": [24, 15, 25, 30],
    "location": [13, 8, 4, 2],
    "sales": [34523, 12345, 39324, 41234]
}, index=["Dallas", "Austin", "Fort Worth", "Houston"])

In [15]:
##3

In [13]:
mydf

            employees  location  sales
Dallas             24        13  34523
Austin             15         8  12345
Fort Worth         25         4  39324
Houston            30         2  41234

In [14]:
mydf["employees"]

Dallas        24
Austin        15
Fort Worth    25
Houston       30
Name: employees, dtype: int64

In [16]:
mydf.loc["Dallas"]

employees       24
location        13
sales        34523
Name: Dallas, dtype: int64

In [17]:
mydf.loc["Dallas", "sales"]

np.int64(34523)

In [18]:
mydf.loc["Dallas", ["sales", "employees"]]

sales        34523
employees       24
Name: Dallas, dtype: int64

In [19]:
mydf[mydf["sales"] > 35000]

            employees  location  sales
Fort Worth         25         4  39324
Houston            30         2  41234

In [20]:
##4

In [27]:
dfIC = pd.read_csv("IceCreamData.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'IceCreamData.csv'